#!/usr/bin/env bash
# bash script that install and configure HAproxy in a load balancer

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
echo -e "listen appname
        bind *:80
        mode http
        balance roundrobin
        server 836-web-01 34.73.121.160:80 check
        server 836-web-02 35.185.87.206:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
