#!/usr/bin/env bash
#Script that uses if, elif and else staments
i=1
while [ $i -lt 11 ]
do

    if [ $i -eq 4 ]
	then
        echo "bad luck"
    elif [ $i -eq 8 ]
	then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$((i+1))
done
