#!/usr/bin/env bash
# Change the user and group of /etc/nginx to execute how that user
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
su nginx -c "service nginx start"
